// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta_banner: dynamic(() => import("./CtaBanner")),
  faq_accordion: dynamic(() => import("./FaqAccordion")),
  feature_grid: dynamic(() => import("./FeatureGrid")),
  hero_section: dynamic(() => import("./HeroSection")),
  logo_cloud: dynamic(() => import("./LogoCloud")),
  pricing_table: dynamic(() => import("./PricingTable")),
  testimonial_band: dynamic(() => import("./TestimonialBand")),
};
